###
GET http://localhost:8080/api/hello
Authorization: Basic cXdlcjoxMjM0
Accept: */*

###
GET http://localhost:8080
Optional-WWW-Authenticate:

###
POST http://localhost:8080/logoutProc

###
GET http://localhost:8080/logoutProc